import { describe, expect, it } from 'vitest'
import { readPaksetInfo } from './simutrans-paksets'
import { isAllowedAssetUrl } from './urls'

const header = `// Generated by "get_pak.sh -generate_h". DO NOT EDIT.
#define PAKSET_COUNT 5
#define OBSOLETE_FROM (4)
paksetinfo_t pakinfo[PAKSET_COUNT] = {
	{ "http://downloads.sourceforge.net/project/simutrans/pak64/125-0/simupak64-125-0.zip", "pak", "pak64 125.0 r2234M", 16552 },
	{ "https://github.com/wa-st/pak-nippon/releases/download/v0.6.2/pak.nippon-v0.6.2.zip", "pak.nippon", "pak.nippon v0.6.2", 50198 },
	{ "http://pak128.jpn.org/souko/pak128.japan.120.0.cab", "pak128.japan", "Pak128.Japan 120.0", 27780 },
	{ "http://example.org/x.zip", "../escape", "x", 1 },
	{ "http://downloads.sourceforge.net/project/simutrans/pak32.comic/pak32.comic_102-0.zip", "pak32", "", 3420 },
};`

describe('Simutrans paksets', () => {
  it('keeps current sets that come as a zip, over https', () => {
    const { mods, downloads } = readPaksetInfo(header)
    expect(mods.map((mod) => mod.id)).toEqual(['pak', 'pak.nippon'])
    expect(mods[0]).toMatchObject({ name: 'pak64', version: 'pak64 125.0 r2234M', size: 16552 * 1024, category: 'Pakset' })
    expect(mods[0].description).not.toBe('')
    expect(downloads.pak).toBe('https://downloads.sourceforge.net/project/simutrans/pak64/125-0/simupak64-125-0.zip')
  })

  it('downloads from the places paksets are hosted', () => {
    for (const url of [
      'https://downloads.sourceforge.net/project/simutrans/pak64/125-0/simupak64-125-0.zip',
      'https://twds.dl.sourceforge.net/project/simutrans/pak64/125-0/simupak64-125-0.zip?viasf=1',
      'https://simutrans-germany.com/pak.german/pak64.german_0-124-5-1-1_full.zip',
      'https://codeberg.org/Nazalassa/pak48.bitlit/releases/download/0.1d/pak48.bitlit_0.1d.zip'
    ]) {
      expect(isAllowedAssetUrl(url)).toBe(true)
    }
    expect(isAllowedAssetUrl('https://dl.sourceforge.net.example.org/x.zip')).toBe(false)
    expect(isAllowedAssetUrl('http://downloads.sourceforge.net/x.zip')).toBe(false)
  })
})
